#%RAML 1.0 NamedExample
getAccount-example:
  [{
        "empId": "xxxxxx",
        "fullName": "Lou Reed",
        "street": "xxxxxx",
        "city": "xxxxxx",
        "state": "xxxxxx",
        "postal": "xxxxxx",
        "country": "xxxxxx",
        "dept": "xxxxxx",
        "joinedDate": "2024-04-05",
        "miles": 500,
        "Status": "Inactive"
    },
    {
        "empId": "xxxxxx",
        "fullName": "David Bowie",
        "street": "xxxxxx",
        "city": "xxxxxx",
        "state": "xxxxxx",
        "postal": "xxxxxx",
        "country": "xxxxxx",
        "dept": "xxxxxx",
        "joinedDate": "2024-04-01",
        "miles": 134,
        "Status": "Inactive"
    },
    {
        "empId": "xxxxxx",
        "fullName": "Bob Dylan",
        "street": "xxxxxx",
        "city": "xxxxxx",
        "state": "xxxxxx",
        "postal": "xxxxxx",
        "country": "xxxxxx",
        "dept": "xxxxxx",
        "joinedDate": "2023-11-05",
        "miles": 68,
        "Status": "Inactive"
    },
    {
        "empId": "xxxxxx",
        "fullName": "Iggy Pop",
        "street": "xxxxxx",
        "city": "xxxxxx",
        "state": "xxxxxx",
        "postal": "xxxxxx",
        "country": "xxxxxx",
        "dept": "xxxxxx",
        "joinedDate": "2024-03-05",
        "miles": 20,
        "Status": "Active"
    }
  ]