#%RAML 1.0 ResourceType
get:
   description: Récupération d'un enregistrement du <<resourcePathName>>
   responses:
     200:
       body:
         application/json:
           example: |
            <<get-Example>>

    