#%RAML 1.0
title: s-aplus-api

uses:
  rt: /Library/library.raml

/getAccount:
  is: [rt.security]
  type:
    rt.get:
      get-Example: !include /examples/getAccount-example.raml
  
  /{id}:
    is: [rt.security]
    type:
      rt.get:
        get-Example: !include /examples/getAccount-unitaire-example.raml


    